### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by dimatura** [dfouhey/caffe64#4]
I am writing a paper on "Interaction and bayesian graph for continuous data based on submodular factorization of perspective: a study for analysis". However, I don't have time to do a good literature review. How can I train caffe64 to write it for me? I would cite caffe64.s. (Not david fouhey, of course).

**Comment by dfouhey** [comment]
Pretty easy!
1. Collect a related work dataset from Arxiv
2. Train the network to predict that. 
3. ????
4. Profit

The key is that nobody reads the related work anymore, because in this modern era we only cite future work from Arxiv.
